// Generated by scripts/gen-speed-table.ts from the formula in kb/product/game-rules.md.
// Do not edit: change the formula in speed-table-gen.ts and regenerate.

/** Rows a piece falls per tick at levels 1–20 (index 0 is level 1), in 16.16 fixed point. */
export const ROWS_PER_TICK: readonly number[] = [
  1093, // level 1: 0.0167 rows/tick
  1378, // level 2: 0.0210 rows/tick
  1769, // level 3: 0.0270 rows/tick
  2311, // level 4: 0.0353 rows/tick
  3076, // level 5: 0.0469 rows/tick
  4169, // level 6: 0.0636 rows/tick
  5759, // level 7: 0.0879 rows/tick
  8107, // level 8: 0.1237 rows/tick
  11635, // level 9: 0.1775 rows/tick
  17027, // level 10: 0.2598 rows/tick
  25416, // level 11: 0.3878 rows/tick
  38709, // level 12: 0.5907 rows/tick
  60169, // level 13: 0.9181 rows/tick
  95484, // level 14: 1.4570 rows/tick
  154743, // level 15: 2.3612 rows/tick
  256187, // level 16: 3.9091 rows/tick
  433425, // level 17: 6.6135 rows/tick
  749597, // level 18: 11.4379 rows/tick
  1325717, // level 19: 20.2288 rows/tick
  2398490, // level 20: 36.5981 rows/tick
];
