// Generates the gravity table from the formula in kb/product/game-rules.md ("Speed curve"). It
// runs only when the table is regenerated (scripts/gen-speed-table.ts) and in the test that
// checks the committed table; the engine itself reads speed-table.ts and never calls Math.pow.

/** 16.16 fixed point: this value is one row per tick. */
export const FIXED_ONE = 65536;

/** Seconds a piece takes to fall one row at `level`. */
export const secondsPerRow = (level: number): number =>
  Math.pow(Math.max(0.05, 0.8 - (level - 1) * 0.007), level - 1);

/**
 * Rows per tick for levels 1 to `levels`, in 16.16 fixed point, rounded up so a level never
 * falls slower than the formula (level 1 is exactly one row every 60 ticks).
 */
export function generateSpeedTable(levels = 20, tps = 60): number[] {
  return Array.from({ length: levels }, (_, i) =>
    Math.ceil(FIXED_ONE / (secondsPerRow(i + 1) * tps)),
  );
}

/** The source of speed-table.ts for `table`. */
export function renderSpeedTable(table: readonly number[]): string {
  const rows = table.map(
    (v, i) => `  ${v}, // level ${i + 1}: ${(v / FIXED_ONE).toFixed(4)} rows/tick`,
  );
  return [
    '// Generated by scripts/gen-speed-table.ts from the formula in kb/product/game-rules.md.',
    '// Do not edit: change the formula in speed-table-gen.ts and regenerate.',
    '',
    '/** Rows a piece falls per tick at levels 1–20 (index 0 is level 1), in 16.16 fixed point. */',
    'export const ROWS_PER_TICK: readonly number[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
}
